version: "3.9"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: "root"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
      # - "--storage.tsdb.retention.time=15d"   # opcional
      # - "--log.level=info"
    ports:
      - "9090:9090"
    environment:
      - TZ=${TZ:-America/Argentina/Buenos_Aires}
    networks:
      - mon_net
    restart: unless-stopped
    volumes:
      # ðŸ‘‰ archivo de config en el host (Â¡absoluto!)
      - /opt/stacks/labo2/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      # ðŸ‘‰ datos persistentes (en el host o volumen nombrado)
      - /opt/stacks/labo2/prometheus/data:/prometheus
      # ðŸ‘‰ si usÃ¡s archivos extras
      # - /opt/stacks/labo2/prometheus/files:/etc/prometheus/files:ro

networks:
  mon_net:
    external: true
