version: "3.9"
services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_SERVER_DOMAIN=${GRAFANA_DOMAIN}
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/
      - TZ=${TZ}
    volumes:
    
      # - /opt/stacks/labo2/grafana/data:/var/lib/grafana
      # si quer√©s auto-provisionar el datasource:
      - /opt/stacks/labo2/grafana/provisioning:/etc/grafana/provisioning:ro

     # - grafana_data:/var/lib/grafana
     # - ./provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
    networks:
      - mon_net
    restart: unless-stopped

volumes:
  grafana_data:

networks:
  mon_net:
    external: true
